### ISSUE TITLE
File indexed.idx not found

### ISSUE THREAD

**Issue by gokhalesushant65** [cyberImperial/attack-graphs#74]
Trying to run the following command after which get the following error:
> sudo python3 setup.py test
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/mtech/attack-graphs/database/indexed.idx'

How to resolve?

**Comment by danalex97** [comment]
Try to run cd `python3 load.py -r` in the directory `/home/dell/mtech/attack-graphs/database`.
