### ISSUE TITLE
‘make test’ command error

### ISSUE THREAD

**Issue by king-zkai** [cyberImperial/attack-graphs#75]
Trying to run the following command after which get the following error:
root@zkai-virtual-machine:/home/zkai/Documents/attack-graphs-master# make test
wget -O tests/topology/discovery/parser/Catch.hpp https://raw.githubusercontent.com/cyberImperial/Catch2/master/single_include/catch2/catch.hpp
--2020-04-17 12:56:45--  https://raw.githubusercontent.com/cyberImperial/Catch2/master/single_include/catch2/catch.hpp
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.
Makefile:17: recipe for target 'catch.o' failed
make: *** [catch.o] Error 4

How to resolve? Thank you!

**Comment by danalex97** [comment]
It looks like you cannot download https://raw.githubusercontent.com/cyberImperial/Catch2/master/single_include/catch2/catch.hpp via wget for some reason.

You could of course just download the single include https://raw.githubusercontent.com/cyberImperial/Catch2/master/single_include/catch2/catch.hpp, put it in the right place and compile the object `cache.o` separately:
```
g++ -std=c++11 -lboost_system -lboost_filesystem -c tests/topology/discovery/parser/Runner.cpp -o catch.o
```

You can just take a look at the makefile, it's really short.
